### Comparing newly matched PB voter data to the original data up on the spreadsheet. 
### Need to run the reshape code from the pbvoters_regression.R file (get to creating pb_long, prior to joining census data)


#run reshape for the original data
pb_long_orig <- pb_long

# rerun reshape with the new data (replacing pb_long with the pb_long generated by updated data)

# inner join to get only voters and years shared across the data frames
pb_both <- pb_long_orig %>% group_by() %>% mutate(VANID = as.numeric(VANID)) %>% 
  inner_join(pb_long, by = c("VANID" = "VANID", "year" = "year"))

# compare the votes across the two:

# Are individuals' voting years shared by each?
table(pb_both$pb.x, pb_both$pb.y)

# how does the distribution of votes in each year compare across the two datasets?
table(pb_both$pb.x, pb_both$pb.y, pb_both$year)

## This is a lot of mismatched data.  Questions have been raised.....  Where did the data for the original DB come from and why is it so different?  
## I'm also skeptical as the number of voters in years 2012-2014 in the original data are identitcal at 1917, which seems questionable.



