---
title: "PB Voters"
author: "Carolina Johnson"
date: "May 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r prelims}
library(RColorBrewer)
library(dplyr)
library(sp)
library(ggmap)
library(leaflet)
library(htmlwidgets)

source("credentials.R")
source("dbDownload.R")

data <- dbDownload(table = "pb", username = username, password = password, dbname = db.name, host = hostname, port = port)

geodata <- data %>% filter(!is.na(Long) & !is.na(Lat))

### making spatial points dataframe ###
xy <- geodata %>% select(Long, Lat) %>% as.matrix()
proj_string <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
geodata <- geodata %>% select(-Long, -Lat)
geodata <- SpatialPointsDataFrame(xy, geodata)
```

## Interactive map of PB voters
```{r}
bpal <- brewer.pal(length(unique(geodata$Race)), "Set1")
pal <- colorFactor(bpal, domain = unique(geodata$Race))



m <- leaflet(geodata, width = "100%") %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addCircleMarkers(clusterOptions = markerClusterOptions(), 
    color = ~pal(Race)
  ) 

m
```

## Alternative map with static points, colored by modelled race

```{r}

m <- leaflet(geodata,  width = "100%") %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addCircles(#clusterOptions = markerClusterOptions(), 
                   color = ~pal(Race)
                   ) %>%
  addLegend("bottomright", pal = pal, values = ~Race,
            title = "Race")
  
m

```

